### ISSUE TITLE
Dupes

### ISSUE THREAD

**Issue by FrostStormRage** [TheUnderTaker11/Better-Magnets#1]
(As title suggests)

Better Magnets mod 1.11.2

A block that are placed on the hopper gets a "copy" of it self, happens when better magnet is active. Works only with only one block but you get a dupe.

**Comment by TheUnderTaker11** [comment]
I will be fixing this for the 1.12 iteration this weekend, won't be going back to 1.11 versions though.

**Comment by TheUnderTaker11** [comment]
Turns out I was dumb and didn't upload basically all of my code, so it might be awhile before I feel like coming back around to it.

**Comment by FrostStormRage** [comment]
oke, no probs.

**Comment by FrostStormRage** [comment]
Oh olso, best magnet to date! (No kidding!!)

**Comment by TheUnderTaker11** [comment]
Haha yeah super useful, I'll try and work on it after finals.

**Comment by TheUnderTaker11** [comment]
Added chat indicator for if you just enabled or disabled the magnet, added anti magnet item, and fixed dupe bug.

**Comment by FrostStormRage** [comment]
AWESOME :) :) :)
