### ISSUE TITLE
Magnets appear everywhere in creative

### ISSUE THREAD

**Issue by Dissgruntled** [TheUnderTaker11/Better-Magnets#3]
Better Magnets MC 1.12.x v1.11
Forge 1.12.2 - 14.23.5.2814

When in creative mode, magnets are listed in every tab and also appear in the trash slot.
https://i.imgur.com/PPeIraW.png
https://i.imgur.com/LH8Ewr3.png
https://i.imgur.com/GlBCA2o.png
Not a huge deal, just wanted to pass this along in case you were unaware.

**Comment by TheUnderTaker11** [comment]
Thanks, Ill look into it when I can.

**Comment by TheUnderTaker11** [comment]
Fixed, probably won't bother releasing the fix for a bit though cause it only matters when in creative anyways.

**Comment by TheUnderTaker11** [comment]
This was fixed awhile ago.
